package by.training.task04.controller.command;

public enum CommandName {
    WRONG_REQUEST, GENERATE_DATA, BLOCK_ACTIVATE_ALL, BLOCK_ACTIVATE_BY_ID, CALC_BALANCE_SUM, FIND_BY_ACCOUNT_NUMBER,
    FIND_BY_FIO, SORT_DATA, FILTER_STATUS, FILTER_AMOUNT,

}
