package by.training.decomposition.controller.command;

public enum CommandName {
    WRONG_REQUEST, MULTIPLY_MATRIX_ON_VALUE,MULTIPLY_MATRICES, TRANSPOSE_MATRIX, SUM_OR_DIFF_MATRICES, BUBBLE_SORT,
    BINARY_MERGE_SORT, INSERT_SORT, SHAKER_SORT, SHELL_SORT, SIMPLE_SELECTION_SORT,

}
